### ISSUE TITLE
ValueError when model testing 

### ISSUE THREAD

**Issue by genuinwix** [lishen/end2end-all-conv#16]
I encountered the following error
`
ValueError: not enough values to unpack (expected 3, got 2)` when accessing  
`index_array, current_index, current_batch_size = next(self.index_generator)` in line 1203 in `dm_image.py`

This happens in both fine tuning phase and model testing phase (as executing in  "Example_model_test.ipynb" notebook inside ddsm_train folder)

Is there anyone also encountered this issue and resolved it?

**Comment by lishen** [comment]
This is the same error as issue #7 You'll have to downgrade your Keras to <2.1.0.
