### ISSUE TITLE
What's the order of the patch classifier predictions?

### ISSUE THREAD

**Issue by frfa1** [lishen/end2end-all-conv#25]
Is it noted in the paper, that the patch classifiers are all trained to predict the following classes: _background, malignant mass, benign mass, malignant calcification and benign calcification_. It seem consistent with the model prediction outputs of the patch classifiers in the Google Drive, which has a size of 5 output classes.

But **how do we check which class each of the patch model outputs are associated with**? I.e. what is the ordering of the outputs.

**Comment by frfa1** [comment]
So to clarify: I'm using the `get_prob_heatmap` function in `dm_image.py` to get the heatmap of an image. The function output is 3-dimensional with the last dimension being 5: (..., ..., 5). Each of those 5 correnspond to a heatmap for one of the classes. But I'm unsure of the order? 

The patch training scripts are set up to train three classes: (background, malignant, benign). 

If you could clarify this, I would be so happy, as I'm using the heatmaps in a thesis.

best regards

**Comment by lishen** [comment]
off the top of my head, the order should be: background, benign calcification, malignant calcification, benign mass, malignant mass.

**Comment by frfa1** [comment]
Do you have any way to confirm this?

A weak link: In the paper the ordering is: background, malignant mass, benign mass, malignant calcification and benign calcification.

This is a different order. So just want to be sure :-))

**Comment by lishen** [comment]
> Do you have any way to confirm this?
> 
> A weak link: In the paper the ordering is: background, malignant mass, benign mass, malignant calcification and benign calcification.
> 
> This is a different order. So just want to be sure :-))

Yes, I can confirm that. Refer to the Fig. 2 and Fig. 4 of the original paper.
