### ISSUE TITLE
Too many values to unpack in calculation step

### ISSUE THREAD

**Issue by nerdykamil** [lishen/end2end-all-conv#7]
Hey, thank you for this work. I have been trying to reproduce the results with Calc_Test and Mass_Test but at the calculation step I keep getting the following error. Can you suggest what I might be doing wrong here.
![screenshot from 2018-07-04 17-04-14](https://user-images.githubusercontent.com/19584358/42276256-a3396e8a-7fac-11e8-9a85-020513a21f22.png)

**Comment by zzsd** [comment]
I also have the same problem,could you tell me how to solve it?Thank you!!!

**Comment by yib0liu** [comment]
I got the error of not enough values to unpack at the same place:
`ValueError: not enough values to unpack (expected 3, got 1)
`

**Comment by lucky777song** [comment]
Did you figure it out? I face with exactly the same problem.

**Comment by danieltao** [comment]
I have the same issue, is it fixed?

**Comment by genuinwix** [comment]
Has anyone encountered the following error:

```
"dm_image.py",  line 1203 in next
index_array, current_index, current_batch_size = next(self.index_generator)
ValueError: not enough values to unpack (expected 3, got 2)
```

Has anyone resolved this issue??

**Comment by lishen** [comment]
This has to do with API changes in Keras. The code works with Keras version < 2.1.0. For example, Keras 2.0.8 is known to work.

Sorry for late response.
