### ISSUE TITLE
How do I find ".csv" file?

### ISSUE THREAD

**Issue by wurenzhong** [lishen/end2end-all-conv#8]
Hello~lishen, I have download the CBIS-DDSM dataset from The Cancer Imaging Archive, it's show in the picture:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/41311844/42797526-31e7efca-89c2-11e8-8bd1-1172ba54165e.png">
But it havn't the ".csv" file，does this file need to be created by ourselves? But we just know the information about the patient, side, CC or MLO, there's no more information.
As shown in the above picture, the test and train sets are scattered throughout the folder, and  they contain many subfolders, I don't know how to set the parameter of "train_dir", "test_dir", "val_dir".

So~I have two requests:
  1:Would you please provide the ".csv" file?
  2:Would you tell us, does we need to sort out the data by ourselves and integrate all the images into the "test_set", "train_set", "val_set" three folders?

Thank you for your time, best wishes for you!

**Comment by bintykhany** [comment]
> Hello~lishen, I have download the CBIS-DDSM dataset from The Cancer Imaging Archive, it's show in the picture:
> <img alt="image" width="237" src="https://user-images.githubusercontent.com/41311844/42797526-31e7efca-89c2-11e8-8bd1-1172ba54165e.png">
> But it havn't the ".csv" file，does this file need to be created by ourselves? But we just know the information about the patient, side, CC or MLO, there's no more information.
> As shown in the above picture, the test and train sets are scattered throughout the folder, and they contain many subfolders, I don't know how to set the parameter of "train_dir", "test_dir", "val_dir".
> 
> So~I have two requests:
> 1:Would you please provide the ".csv" file?
> 2:Would you tell us, does we need to sort out the data by ourselves and integrate all the images into the "test_set", "train_set", "val_set" three folders?
> 
> Thank you for your time, best wishes for you!

I just start working on this... i have the same question.. from where i get .csv files

**Comment by wurenzhong** [comment]
@bintykhany 
You can get the .csv from https://wiki.cancerimagingarchive.net/display/Public/CBIS-DDSM#188b4eabd7024bc68ab11c4d4150cb01
![image](https://user-images.githubusercontent.com/41311844/61256894-2a22ae80-a7a1-11e9-9e8b-f7c199ddf5ee.png)
![image](https://user-images.githubusercontent.com/41311844/61256906-373f9d80-a7a1-11e9-9e39-f9e73b377c91.png)

**Comment by bintykhany** [comment]
> @bintykhany
> You can get the .csv from https://wiki.cancerimagingarchive.net/display/Public/CBIS-DDSM#188b4eabd7024bc68ab11c4d4150cb01
> ![image](https://user-images.githubusercontent.com/41311844/61256894-2a22ae80-a7a1-11e9-9e8b-f7c199ddf5ee.png)
> ![image](https://user-images.githubusercontent.com/41311844/61256906-373f9d80-a7a1-11e9-9e39-f9e73b377c91.png)

@wurenzhong  thanks a lot ..

**Comment by bintykhany** [comment]
@wurenzhong  Thanks a lot..

**Comment by RanChiVo** [comment]
I am also a beginner, please help me answer the question 2:
"2:Would you tell us, does we need to sort out the data by ourselves and integrate all the images into the "test_set", "train_set", "val_set" three folders?" 
Thank you.

**Comment by wurenzhong** [comment]
@RanChiVo Yes, these data sets need to be organized by ourselves. First, you can write a "for" loop to rename all the image names (e.g. "00000 ") to folder names (e.g. " mass-test_p_00707_right_cc ") and put them in the same folder. Then, divide them into "test_set", "train_set", "val_set" based on the ".csv" files.  Finally, assign the file address.

**Comment by RanChiVo** [comment]
I will try your way that helped me. I hope I can handle it.
“That’s very kind of you. Thank you.”

**Comment by RanChiVo** [comment]
@wurenzhong  
Follow the author's instructions in the example_model_test file.
"On your machine, you shall have folders like the following:

./full_test_1152x896
./full_test_1152x896/neg
./full_test_1152x896/pos
The "neg" being the negative images and "pos" being the positive images."

I have to rely on the test.csv file to classify the image of which class, right? neg or pos. 
Can you explain it clearly to me? Thank you very much.

**Comment by wurenzhong** [comment]
@RanChiVo 
The "test_set", "train_set" and "val_set" folders all have "neg', "pos" subfolders, and images are in subfolders. Sorry, It's been so long since I ran this code that I kind of forgot. Data sets can be divided according to the website of https://wiki.cancerimagingarchive.net/display/Public/CBIS-DDSM#188b4eabd7024bc68ab11c4d4150cb01

**Comment by Marim1731** [comment]
did you run the rename and creation of  "test_set", "train_set", "val_set" code ?

**Comment by Tianshuo-Xu** [comment]
@wurenzhong Hi, I have the same question, what is the meaning of "neg" and "pos"? Because I want to test on my own dataset.

**Comment by wurenzhong** [comment]
@Tianshuo-Xu “neg” and "pos" are labels, negative and positive abbreviations

**Comment by Tianshuo-Xu** [comment]
@wurenzhong I still dont understand the positive and negative, is the positive means benign? and negative means malignant? Can you give a pathology explanation for "pos" and "neg"? Thanks!

**Comment by wurenzhong** [comment]
@ Tianshuo-Xu 
positive means malignant, and negative means benign.

**Comment by Tianshuo-Xu** [comment]
@wurenzhong Thanks a lot for your explanation! I run the model using a single MG image, and the model output two points like that: [0.0003127959, 0.99998164]. What are this two points mean?

**Comment by wurenzhong** [comment]
@Tianshuo-Xu
It means loss and accuracy

**Comment by JeffSaa** [comment]
I just downloaded this dataset but the files are named eg 1-1.dcm and in the csv file are named differently. Anyone solved this?
